/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelomp5;

/**
 *
 * @author cherly
 */
public class cherlyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form cherlyJFrame
     */
    public cherlyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tFoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Nama ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 140, 35, 16);

        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("NIM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 170, 23, 16);

        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 200, 37, 16);

        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Link Github");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 230, 59, 16);

        tFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Uji Coba.png"))); // NOI18N
        tFoto.setText("Foto");
        tFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFotoMouseClicked(evt);
            }
        });
        getContentPane().add(tFoto);
        tFoto.setBounds(170, 100, 150, 210);

        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText(":  Cherly Ma'rifatul Ulwiyah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 140, 139, 16);

        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText(":  https://github.com/Cherly23/kelomp5.git");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 230, 270, 16);

        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText(":  202457201017");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 170, 140, 16);

        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText(":  Ds.Sombron Loceret Nganjuk");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 200, 165, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("PROFIL CHERLY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 140, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/power back.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 310, 52, 50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PPT Netral.jpeg"))); // NOI18N
        jLabel12.setRequestFocusEnabled(false);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 700, 400);

        btnTutup.setBackground(new java.awt.Color(0, 51, 51));
        btnTutup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTutup.setForeground(new java.awt.Color(204, 255, 255));
        btnTutup.setText("BACK");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(btnTutup);
        btnTutup.setBounds(370, 310, 50, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFotoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tFotoMouseClicked

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cherlyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cherlyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cherlyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cherlyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cherlyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tFoto;
    // End of variables declaration//GEN-END:variables
}
