/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelomp5;

/**
 *
 * @author HP
 */
public class icul extends javax.swing.JFrame {

    /**
     * Creates new form icul
     */
    public icul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LinkGithub = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProfilIchul = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        NIM = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        Nama1 = new javax.swing.JLabel();
        NIM1 = new javax.swing.JLabel();
        Alamat1 = new javax.swing.JLabel();
        Alamat2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LinkGithub.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LinkGithub.setForeground(new java.awt.Color(102, 204, 255));
        LinkGithub.setText("Link Github :");
        getContentPane().add(LinkGithub, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 90, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelomp5/ich.jpg"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/kelomp5/ich.jpg"))); // NOI18N
        jLabel3.setFocusable(false);
        jLabel3.setRequestFocusEnabled(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 200));

        ProfilIchul.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        ProfilIchul.setForeground(new java.awt.Color(102, 204, 255));
        ProfilIchul.setText("PROFIL ICHUL");
        getContentPane().add(ProfilIchul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 210, 28));

        Nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nama.setForeground(new java.awt.Color(102, 204, 255));
        Nama.setText("Achmad Muslichul Anwar");
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 190, 28));

        NIM.setForeground(new java.awt.Color(102, 204, 255));
        NIM.setText("202457201002");
        getContentPane().add(NIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 130, 28));

        Alamat.setForeground(new java.awt.Color(102, 204, 255));
        Alamat.setText("Kec. Tanjunganom");
        getContentPane().add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 200, 28));

        Nama1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Nama1.setForeground(new java.awt.Color(102, 204, 255));
        Nama1.setText("Nama          :");
        getContentPane().add(Nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 28));

        NIM1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        NIM1.setForeground(new java.awt.Color(102, 204, 255));
        NIM1.setText("NIM             :");
        getContentPane().add(NIM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 90, 28));

        Alamat1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Alamat1.setForeground(new java.awt.Color(102, 204, 255));
        Alamat1.setText("Alamat        :");
        getContentPane().add(Alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 90, 28));

        Alamat2.setForeground(new java.awt.Color(102, 204, 255));
        Alamat2.setText("Dsn. Krajan Patuk Ds. Kampungbaru");
        getContentPane().add(Alamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 200, 28));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelomp5/WhatsApp Image 2025-09-14 at 14.26.49.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(icul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(icul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(icul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(icul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new icul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Alamat1;
    private javax.swing.JLabel Alamat2;
    private javax.swing.JLabel LinkGithub;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel NIM1;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama1;
    private javax.swing.JLabel ProfilIchul;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
