/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelomp5;

/**
 *
 * @author cherly
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        cherly = new javax.swing.JButton();
        aziz = new javax.swing.JButton();
        ikhul = new javax.swing.JButton();
        azka = new javax.swing.JButton();
        toni = new javax.swing.JButton();
        cialin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Halaman Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        btnTutup.setBackground(new java.awt.Color(0, 0, 153));
        btnTutup.setForeground(new java.awt.Color(255, 255, 255));
        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(btnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 120, 30));

        cherly.setText("CHERLY");
        cherly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherlyActionPerformed(evt);
            }
        });
        getContentPane().add(cherly, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 200, 50));

        aziz.setText("AZIZ");
        getContentPane().add(aziz, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 200, 40));

        ikhul.setText("ICUL");
        ikhul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikhulActionPerformed(evt);
            }
        });
        getContentPane().add(ikhul, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 200, 50));

        azka.setText("AZKA");
        getContentPane().add(azka, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 210, 50));

        toni.setText("TONI");
        toni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toniActionPerformed(evt);
            }
        });
        getContentPane().add(toni, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 210, 40));

        cialin.setText("CIALIN");
        getContentPane().add(cialin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 210, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cherlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherlyActionPerformed
        // TODO add your handling code here:
        new cherlyJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_cherlyActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnTutupActionPerformed

    private void ikhulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikhulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ikhulActionPerformed

    private void toniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aziz;
    private javax.swing.JButton azka;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton cherly;
    private javax.swing.JButton cialin;
    private javax.swing.JButton ikhul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton toni;
    // End of variables declaration//GEN-END:variables
}
